# Generated by Django 5.1.1 on 2024-10-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaEcommerce',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('addresses', models.JSONField(default=list)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=100)),
                ('product_subcategory', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_stock', models.IntegerField()),
                ('product_ratings', models.JSONField(default=list)),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('shipping_method', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact_name', models.CharField(max_length=255)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('warehouse_id', models.IntegerField()),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('shelf_number', models.CharField(max_length=50)),
                ('reorder_point', models.IntegerField()),
                ('support_ticket_id', models.IntegerField(blank=True, null=True)),
                ('support_ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('support_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_id', models.IntegerField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wishlist_items', models.JSONField(default=list)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='contents_me_usernam_8e90f0_idx'), models.Index(fields=['email'], name='contents_me_email_72532d_idx'), models.Index(fields=['order_id'], name='contents_me_order_i_dc68f5_idx'), models.Index(fields=['product_id'], name='contents_me_product_20bdf7_idx'), models.Index(fields=['payment_id'], name='contents_me_payment_38dc65_idx')],
                'unique_together': {('user_id', 'order_id', 'product_id')},
            },
        ),
    ]
